version: "2.3"

services:
  master:
    build:
      context: ../../
      dockerfile: ./${MODULE}/${TRAINING}/Dockerfile
    image: sbeliakou/lab-${MODULE}:${TRAINING}
    container_name: master
    hostname: master
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/lib/containerd
      - ./tasks:/var/_data/tasks
    tmpfs:
      - /run
      - /tmp
    ports:
      - 8022:8022
      - 9090:9090
      - 8081:8081
      - 8001:8001
      - 80:80
      - 443:443
      - 8443:6443
      - 30080-30100:30080-30100
    env_file:
      - ~/.student
    environment:
      TRAINING: kubernetes
      LAB: "cluster-init"
      ANALYTICS: ecsc00a05b03.epam.com
    labels:
      lab.devops: yes
      lab.name: ${MODULE}:${TRAINING}
      lab.env: ${PWD}
    privileged: true
    cpus: 0.75
    ipc: private
    tty: true
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    networks:
      k8slocal:
        ipv4_address: 172.31.0.2

  node01:
    image: sbeliakou/lab-k8s-node:latest
    hostname: node01
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cpus: 0.5
    ipc: private
    tty: true
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    depends_on:
      - master
    networks:
      k8slocal:
        ipv4_address: 172.31.0.3

networks:
  k8slocal:
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
        gateway: 172.31.0.1
