- name: create course directory
  file:
    path: "{{ path }}/{{ module.name }}/{{ course.course_id }}"
    state: directory

- name: create course index.json
  template:
    src: course_index.json.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/index.json"

- name: create intro.md
  template:
    src: intro.md.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/intro.md"

- name: create finish.md
  template:
    src: finish.md.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/finish.md"

- name: create runPrep.sh
  template:
    src: runPrep.sh.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/runPrep.sh"

- name: create step*.md
  template:
    src: step.md.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/step{{ item.0 }}.md"
  with_indexed_items: "{{ course.steps }}"

- name: create step*-courseData.sh
  template:
    src: step-courseData.sh.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/step{{ item.0 }}-courseData.sh"
  with_indexed_items: "{{ course.steps }}"

- name: create step*-foreground.sh
  template:
    src: step-foreground.sh.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/step{{ item.0 }}-foreground.sh"
  with_indexed_items: "{{ course.steps }}"

- name: create step*-verify.sh
  template:
    src: step-verify.sh.j2
    dest: "{{ path }}/{{ module.name }}/{{ course.course_id }}/step{{ item.0 }}-verify.sh"
  with_indexed_items: "{{ course.steps }}"

