- name: DevOps Lab
  hosts: localhost

  vars:
  - path: "$HOME/devops-katakoda"
  vars_files:
  - kat_example.yaml

  tasks:
  - name: Create the common directory
    file:
      path: "{{ path }}"
      state: directory

  - include_role: 
      name: module_creator
    vars:
    - module_content: "{{ module }}"
    - module_path: "{{ path }}"
    loop: "{{ modules }}"
    loop_control:
      loop_var: module
