- hosts: localhost
  tasks:
  - name: Create the course directory
    file:
      path: devops-katacoda
      state: directory

- name: Kubernetes
  hosts: localhost
  vars:
    path: devops-katacoda
  vars_files:
  - courses/kubernetes.yaml
  tasks:
  - name: creating pathway json
    template:
      src: module_index.json.j2
      dest: "{{ path }}/{{ module.name }}-pathway.json"
  - name: create module directory
    file:
      path: "{{ path }}/{{ module.name }}"
      state: directory
  - name: filling the courses
    include_tasks: tasks/course_tasks.yaml
    loop: "{{ module.courses }}"
    loop_control:
      loop_var: course
    













#  - debug: msg={{ kubernetes }}



    



#  - include_role: 
#      name: module_creator
#    vars:
#    - module_content: "{{ module }}"
#    - module_path: "{{ path }}"
#    loop: "{{ modules }}"
#    loop_control:
#      loop_var: module
