- name: Kubernetes
  hosts: localhost
  tags: k8s
  vars:
    path: "{{ playbook_dir }}/.."
  vars_files:
  - "{{ path }}/courses/kubernetes.yaml"
  tasks:
  - name: create kubernetes pathway.json
    template:
      src: module_index.json.j2
      dest: "{{ path }}/{{ module.name }}-pathway.json"
    
  - name: create kubernetes module directory
    file:
      path: "{{ path }}/{{ module.name }}"
      state: directory
    
  - name: create kubernetes courses
    include_tasks: tasks/course_tasks.yaml
    loop: "{{ module.courses }}"
    loop_control:
      loop_var: course


- name: Docker
  hosts: localhost
  tags: docker
  vars:
    path: "{{ playbook_dir }}/.."
  vars_files:
  - "{{ path }}/courses/docker.yaml"
  tasks:
  - name: create docker pathway.json
    template:
      src: module_index.json.j2
      dest: "{{ path }}/{{ module.name }}-pathway.json"
      
  - name: create docker module directory
    file:
      path: "{{ path }}/{{ module.name }}"
      state: directory
      
  - name: create docker courses
    include_tasks: tasks/course_tasks.yaml
    loop: "{{ module.courses }}"
    loop_control:
      loop_var: course


