- hosts: localhost
  tasks:
  - name: Create the course directory
    file:
      path: devops-katacoda
      state: directory

- name: Kubernetes
  hosts: localhost
  vars:
    path: devops-katacoda
  vars_files:
  - courses/kubernetes.yaml
  tasks:
  - name: creating pathway json
    template:
      src: module_index.json.j2
      dest: "{{ path }}/{{ kubernetes.name }}-pathway.json"
  - name: create module directory
    file:
      path: "{{ path }}/{{ kubernetes.name }}"
      state: directory
  - name: filling the courses
    include_tasks: tasks/course_tasks.yaml
    loop: "{{ kubernetes.courses }}"
    loop_control:
      loop_var: course
    
